Repository TWiStErRob/net.twisterrob.ghlint, pull requests merged in 2024-05, with the labels that each got.

#273 Fix #224: Implement duplicate key as "schema validation"
  modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/yaml/YamlValidation.kt
  modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/yaml/detectDuplicateKeys.kt
  modules/ghlint-jsonschema/src/test/kotlin/net/twisterrob/ghlint/yaml/DetectDuplicateKeysKtTest.kt
  modules/ghlint-jsonschema/src/test/kotlin/net/twisterrob/ghlint/yaml/YamlValidationTest.kt
  modules/ghlint-jsonschema/src/test/kotlin/net/twisterrob/ghlint/yaml/matchers-Problem.kt
  modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/yaml/Node.resolve.kt
  modules/ghlint/src/test/kotlin/net/twisterrob/ghlint/analysis/ValidationRuleTest.kt
Labels: in:rules, in:reporting, a:feature

#267 Fix #84: Implement InvalidExpressionUsageRule for `uses:` on actions
  .gitignore
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DefaultRuleSet.kt
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/InvalidExpressionUsageRule.kt
  modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/InvalidExpressionUsageRuleTest.kt
Labels: in:rules, a:feature

#275 Fix #221: abstract .env into an interface with map/text
  modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Env.kt
  modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Job.kt
  modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Step.kt
  modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Workflow.kt
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/EmptyEnvRule.kt
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/MissingGhTokenRule.kt
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/PreferGitHubTokenRule.kt
  modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/EmptyEnvRuleTest.kt
  modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/MissingGhTokenRuleTest.kt
  modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/PreferGitHubTokenRuleTest.kt
  modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeActionStep.kt
  modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeComponentFactory.kt
  modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeEnv.kt
  modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt
  modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeWorkflow.kt
  modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeWorkflowStep.kt
Labels: a:bug, a:enhancement, in:rules, in:core

#276 Replace SchemaStore URLs with public API
  README.md
  modules/ghlint-jsonschema/src/main/kotlin/net/twisterrob/ghlint/yaml/YamlValidation.kt
Labels: a:enhancement, in:dependencies

#281 Fix #247: Implement MissingGhRepoRule
  modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Action.kt
  modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/ActionStep.kt
  modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Job.kt
  modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/Step.kt
  modules/ghlint-api/src/main/kotlin/net/twisterrob/ghlint/model/WorkflowStep.kt
  modules/ghlint-extensions/build.gradle
  modules/ghlint-extensions/src/main/kotlin/net/twisterrob/ghlint/model/isCheckout.kt
  modules/ghlint-extensions/src/main/kotlin/net/twisterrob/ghlint/model/seesEnvVar.kt
  modules/ghlint-extensions/src/main/kotlin/net/twisterrob/ghlint/model/steps.kt
  modules/ghlint-extensions/src/main/kotlin/net/twisterrob/ghlint/model/usesGhCli.kt
  modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/DefaultShellKtTest.kt
  modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/EffectiveShellKtTest.kt
  modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/IsCheckoutKtTest.kt
  modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/SeesEnvVarKtTest.kt
  modules/ghlint-extensions/src/test/kotlin/net/twisterrob/ghlint/model/StepsKtTest.kt
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/DefaultRuleSet.kt
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/MissingGhRepoRule.kt
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/MissingGhTokenRule.kt
  modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/MissingGhRepoRuleTest.kt
  modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/MissingGhTokenRuleTest.kt
  modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeJob.kt
  modules/ghlint-snakeyaml/src/main/kotlin/net/twisterrob/ghlint/model/SnakeRuns.kt
  modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/check.kt
  modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/load.kt
  modules/ghlint-testing/src/main/kotlin/net/twisterrob/ghlint/testing/validate.kt
Labels: in:rules, a:feature

#283 Fix Java 21+ red wall of text in unit tests with mock()
  gradle/plugins/src/main/kotlin/net/twisterrob/ghlint/build/testing.gradle.kts
Labels: a:bug, in:upstream

#282 Fix #277: ExplicitJobPermissionsRule for redundant workflow permissions
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRule.kt
  modules/ghlint-rules/src/test/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRuleTest.kt
Labels: a:enhancement, in:rules

#290 Fix broken tests in #282: Move example to the other issue
  modules/ghlint-rules/src/main/kotlin/net/twisterrob/ghlint/rules/ExplicitJobPermissionsRule.kt
Labels: a:bug, in:ci

#289 Add a workflow_run trigger on main in preparation for fixing #286
  .github/workflows/ci-publish.yml
Labels: a:enhancement, in:ci
